//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class calamviec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calamviec()
        {
            this.nhanviens = new HashSet<nhanvien>();
        }
    
        public string maca { get; set; }
        public string tenca { get; set; }
        public Nullable<System.TimeSpan> tgianbd { get; set; }
        public Nullable<System.TimeSpan> tgiankt { get; set; }
        public Nullable<int> tthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhanvien> nhanviens { private get; set; }
    }
}
