//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chamcong
    {
        public string macc { get; set; }
        public string manv { get; set; }
        public Nullable<System.DateTime> tgianbd { get; set; }
        public Nullable<System.DateTime> tgiankt { get; set; }
        public Nullable<int> ngaynghi { get; set; }
    
        public virtual nhanvien nhanvien { private get; set; }
    }
}
