//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.hoadons = new HashSet<hoadon>();
        }
    
        public string makh { get; set; }
        public string hoten { get; set; }
        public string dchi { get; set; }
        public Nullable<System.DateTime> ngsinh { get; set; }
        public string sdt { get; set; }
        public string cccd { get; set; }
        public string gioitinh { get; set; }
        public Nullable<int> tthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { private get; set; }
    }
}
