//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_HoaDonTong
    {
        public string mahd { get; set; }
        public string tennv { get; set; }
        public string hoten { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public string tendouong { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
    }
}
